import type { Metadata } from "next";
import { Inter, Roboto, Lato } from "next/font/google";
import "./globals.css";
import "react-multi-carousel/lib/styles.css";
import Header from "@/components/Navbar/Navbar";
import { Suspense } from "react";
import HomeHeaderLoader from "@/components/HomeHeader/HomeHeaderLoader";
const roboto = Roboto({ weight: "100", subsets: ["latin"] });
const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-base-color">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className={`${lato.className} text-white mr-2 mb-2`}>
        <Header />
        <Suspense fallback={<HomeHeaderLoader />}>
          <div className="pt-12 ml-2">{children}</div>
        </Suspense>
      </body>
    </html>
  );
}
