import type { Metadata, Viewport } from "next";
import { Inter, Roboto, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navbar/Navbar";
import { Suspense } from "react";
import HomeHeaderLoader from "@/components/HomeHeader/HomeHeaderLoader";
import NextAuthProvider from "@/components/Providers/NextAuthProvider";
import Head from "next/head";
import NextTopLoader from "nextjs-toploader";
// import { BottomSheetHelper } from "@/components/Dialog/Dialog";
const roboto = Roboto({ weight: "100", subsets: ["latin"] });
const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "black",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.className} text-white mb-2 bg-base-color`}>
        <NextTopLoader zIndex={10000} color="#FF4500" />
        <NextAuthProvider>
          {/* <BottomSheetHelper> */}
          <Header />
          <Suspense fallback={<HomeHeaderLoader />}>
            <div className="pt-12 mx-2">{children}</div>
          </Suspense>
          {/* </BottomSheetHelper> */}
        </NextAuthProvider>
      </body>
    </html>
  );
}
