import type { Metadata } from "next";
import { Inter, Roboto, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navbar/Navbar";
import { Suspense } from "react";
import HomeHeaderLoader from "@/components/HomeHeader/HomeHeaderLoader";
import NextAuthProvider from "@/components/Providers/NextAuthProvider";
const roboto = Roboto({ weight: "100", subsets: ["latin"] });
const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.className} text-white mb-2 bg-base-color`}>
        <NextAuthProvider>
          <Header />
          <Suspense fallback={<HomeHeaderLoader />}>
            <div className="pt-12 ml-2 mr-2">{children}</div>
          </Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
